docker:
  - image: circleci/python
steps:
  - add_ssh_keys:
      fingerprints:
        - "8a:1f:2c:bc:72:b9:ff:e8:a5:04:a1:1d:e6:67:e5:19"
  - run: ssh-keyscan -H smither.org >> ~/.ssh/known_hosts
  - run: ssh gameserv@smither.org "
            cd ~/games/minecraft/opwatch-develop/docker-compose &&
            git fetch && git reset --hard origin/develop &&
            docker-compose -p opwatch_dev kill spigot server &&
            docker-compose -p opwatch_dev rm -f spigot server &&
            docker-compose pull &&
            docker-compose -p opwatch_dev up -d "
  - slack/notify:
           message: "Services deployed on smither.org:8888 and smither.org:25570"
