docker:
  - image: circleci/python
steps:
  - attach_workspace:
      at: ~/opwatch
  - slack/approval:
      message: "Hey, any chance of approval to release $(cat ~/opwatch/.version) on $CIRCLE_PROJECT_REPONAME?"
