docker:
  - image: circleci/python
steps:
  - attach_workspace:
      at: ~/opwatch
  - run:
      name: Get Version
      command: |
        VERSION=$(cat ~/opwatch/.version)
  - slack/approval:
      message: "Hey, any chance of approval to release $VERSION on $CIRCLE_PROJECT_REPONAME?"
