docker:
  - image: circleci/openjdk:8-jdk-stretch
working_directory: ~/opwatch/server
environment:
  JVM_OPTS: -Xmx3200m
  TERM: dumb
steps:
  - checkout:
      path: ~/opwatch
  - run:
      name: Set Version
      working_directory: ~/opwatch
      command: perl -0777 -i.orig -pe "s/MANUAL_BUILD/$(cat .version)/igs" ./server/build.gradle build.gradle
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run: gradle dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
  - run: gradle build -x test
  - run: gradle bootJar
  - persist_to_workspace:
      root: ~/opwatch
      paths:
        - server/Dockerfile
        - server/build/libs
        - server/build/resources
        - .version
  - slack/status:
      fail_only: 'true'
