docker:
  - image: circleci/openjdk:11-jdk-node-browsers
working_directory: ~/opwatch/spigot
environment:
  JVM_OPTS: -Xmx3200m
steps:
  - checkout:
      path: ~/opwatch
  - run:
      name: Set Version
      working_directory: ~/opwatch
      command: perl -0777 -i.orig -pe "s/MANUAL_BUILD/$(cat .version)/igs" ./spigot/build.gradle build.gradle
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run: gradle dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
  - run: gradle build -x test
  - run: gradle shadowJar
  - persist_to_workspace:
      root: ~/opwatch
      paths:
        - spigot/docker
        - spigot/build/libs
        - spigot/build/resources
