docker:
  - image: circleci/openjdk:11-jdk
working_directory: ~/opwatch/server
environment:
  JVM_OPTS: -Xmx3200m
  TERM: dumb
steps:
  - checkout:
      path: ~/opwatch
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run: gradle dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
  - run: gradle check
  - store_artifacts:
      path: build/reports
      destination: build_reports
  - store_test_results:
      path: build/test-results
  - slack/notify:
      message: "Tests complete on $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH. See results HERE -> https://$CIRCLE_BUILD_NUM-$CIRCLE_PROJECT_NUM-gh.circle-artifacts.com/0/reports/tests/test/index.html"
  - slack/status