version: 2
jobs:
  build_server:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/opwatch/server
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout:
          path: ~/opwatch
      - run:
          name: Set Version
          working_directory: ~/opwatch
          command: perl -0777 -i.orig -pe "s/MANUAL_BUILD/$(cat .version)/igs" ./server/build.gradle build.gradle
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle bootJar
      - persist_to_workspace:
          root: ~/opwatch
          paths:
            - server/Dockerfile
            - server/build/libs
            - server/build/resources
            - .version
  test_server:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/opwatch/server
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout:
          path: ~/opwatch
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle check
      - store_artifacts:
          path: build/reports
          destination: build_reports
      - store_test_results:
          path: build/test-results
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout:
          path: ~/opwatch
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ~/opwatch/.version)
            echo $VERSION
            zip ./artifacts/server-$VERSION.zip ./artifacts/server ./artifacts/.version
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/*.zip




workflows:
  version: 2
  build:
    jobs:
      - build_server
      - test_server:
          requires:
            - build_server
      - publish-github-release:
          requires:
            - test_server
          filters:
            branches:
              only: master