version: 2.1

orbs:
  slack: circleci/slack@1.0.0

jobs: 
  build_server:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/opwatch/server
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout:
          path: ~/opwatch
      - run:
          name: Set Version
          working_directory: ~/opwatch
          command: perl -0777 -i.orig -pe "s/MANUAL_BUILD/$(cat .version)/igs" ./server/build.gradle build.gradle
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle bootJar
      - persist_to_workspace:
          root: ~/opwatch
          paths:
            - server/Dockerfile
            - server/build/libs
            - server/build/resources
            - .version
    
  check_circle_config:
    docker:
      - image: circleci/python
    working_directory: ~/opwatch/.circleci
    steps:
      - checkout:
          path: ~/opwatch
      - run: python check_config.py
      - run:
          name: Halt and commit when config changed
          command: |
              git config --global user.email "$GITHUB_EMAIL"
              git config --global user.name "$CIRCLE_USERNAME"
              git add config.yml
              git commit -m "Config Changed: Updating Circle build Config
                https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID
              "
              git push -q https://$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git $CIRCLE_BRANCH
              curl -X POST https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/cancel?circle-token=$CIRCLE_TOKEN
          when: on_fail
    
  deploy_server:
    docker:
      - image: circleci/python
    steps:
      - slack/notify:
          message: "Deploy not yet implemented. Just do it!"
    
  docker_release:
    docker:
      - image: circleci/python:3.6.6-jessie-browsers
    environment:
      REGISTRY: smither/opwatch-server
    steps:
      - attach_workspace:
          at: ~/opwatch
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          working_directory: ~/opwatch/server
          command: docker build -t $REGISTRY:$CIRCLE_SHA1 .
      - run:
          name: Push docker image to docker hub
          command: |
            export VERSION=$(cat ~/opwatch/.version)
            [[ $CIRCLE_BRANCH = "master" ]] && RELEASE="stable" || RELEASE="testing"
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag $REGISTRY:$CIRCLE_SHA1 $REGISTRY:$RELEASE-$VERSION
            docker tag $REGISTRY:$CIRCLE_SHA1 $REGISTRY:$RELEASE
            [[ $CIRCLE_BRANCH = "master" ]] && docker tag $REGISTRY:$CIRCLE_SHA1 $REGISTRY:latest
            docker push $REGISTRY:$CIRCLE_SHA1
            docker push $REGISTRY:$RELEASE-$VERSION
            docker push $REGISTRY:$RELEASE
      - slack/notify:
          message: "${CIRCLE_PROJECT_REPONAME} v$VERSION released on docker hub"
  notify_start:
    docker:
      - image: circleci/python
    steps:
      - slack/notify:
          message: "I am starting a build for $CIRCLE_PROJECT_REPONAME on branch $CIRCLE_BRANCH -> <https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID|WORKFLOW>"
          color: "#195F93"
  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout:
          path: ~/opwatch
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            export VERSION=$(cat ~/opwatch/.version)
            echo $VERSION
            zip ./artifacts/server-$VERSION.zip ./artifacts/server ./artifacts/.version
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/*.zip
      - slack/notify:
          message: "${CIRCLE_PROJECT_REPONAME} v$VERSION released on github"
  request_approval:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: ~/opwatch
      - run:
          name: Get Version
          command: |
            VERSION=$(cat ~/opwatch/.version)
      - slack/notify:
          message: "Hey, any chance of approval to release $VERSION on $CIRCLE_PROJECT_REPONAME? -> https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID"
    
  test_server:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/opwatch/server
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout:
          path: ~/opwatch
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle check
      - store_artifacts:
          path: build/reports
          destination: build_reports
      - store_test_results:
          path: build/test-results
      - slack/status
  

workflows: 
  server:
    jobs:
      - check_circle_config
      - notify_start:
          requires:
            - check_circle_config
      - build_server:
          requires:
            - notify_start
      - test_server:
          requires:
            - build_server
      - docker_release:
          requires:
            - test_server
          filters:
            branches:
              only:
                - develop
                - master
      - deploy_server:
          requires:
            - docker_release
          filters:
            branches:
              only:
                - develop
                - master
      - request_approval:
          requires:
            - test_server
          filters:
            branches:
              only: master
      - release_approval:
          type: approval
          requires:
            - request_approval
          filters:
            branches:
              only: master
      - publish_github_release:
          requires:
            - release_approval
          filters:
            branches:
              only: master
  

notify:
  webhooks:
    - url: https://host/webhook/
