version: "3"
services:
  spigot:
    build: ../spigot
    ports:
      - "25570:25565"
    volumes:
      - "configs/opwatch.yml:/spigot/plugins/opwatch/config.yml"
    env_file:
      - "configs/spigot.env"
  server:
    build: ../server
    ports:
      - "8888:8080"
    depends_on:
      - db
    env_file:
      - "configs/server.env"
  db:
    image: mariadb:10.4.2-bionic
    env_file:
      - "configs/db.env"