jobs:
  - check_circle_config
  - notify_start:
      requires:
        - check_circle_config
  - build_server:
      requires:
        - notify_start
  - test_server:
      requires:
        - build_server
  - docker_release:
      requires:
        - test_server
      filters:
        branches:
          only:
            - develop
            - master
  - deploy_server:
      requires:
        - docker_release
      filters:
        branches:
          only:
            - develop
            - master
  - request_approval:
      requires:
        - test_server
      filters:
        branches:
          only: master
  - release_approval:
      type: approval
      requires:
        - request_approval
      filters:
        branches:
          only: master
  - publish_github_release:
      requires:
        - release_approval
      filters:
        branches:
          only: master